### ISSUE TITLE
Assert on Page method

### ISSUE THREAD

**Issue by Novotnde** [xamarin-automation-service/uitest-pop-example#8]
Hello, 

I have a question when it comes to method Assert on page. I am having issues that once the page is loaded I always get even if the page is loaded

Unable to verify on page: EulaPage
Expected: No Exception to be thrown
But was:   (Trait not set for current platform)

I have followed the example so ia m not very sure where am I making mistake.

Kind Regards,
Denisa

**Comment by Sweekriti91** [comment]
Hi! Based on the error message `But was: (Trait not set for current platform)` it means that the Trait property was not set on the page `EulaPage`. You can see how the Trait is set by looking at the samplehere : https://github.com/xamarin-automation-service/uitest-pop-example/blob/master/Xamarin.UITest.POPSample/Pages/TaskDetailsPage.cs#L19

```
protected override PlatformQuery Trait => new PlatformQuery
        {
            Android = x => x.Marked("menu_save_task"),
            iOS = x => x.Marked("Task Details")
        };
```

**Comment by Novotnde** [comment]
Hello, 

ah I see, thank you, I am sorry I did not notice. Thank you
